port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - lens.l.google.com
  - +.qq.com
  - +.music.163.com
  - localhost
  - +.local
  - +.internal
  - '*.aliyuncs.com'
  - stun.*.*
  - stun.*.*.*
  - +.cdn.jsdelivr.net
  nameservers:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  - 1.1.1.1
  - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 224.0.0.0/4
    - 240.0.0.0/4
proxies:
- name: SS-PziAi
  type: ss
  server: 103.103.245.158
  port: 443
  cipher: aes-256-gcm
  password: ccf426f1fe78
- name: SS-jCUmz
  type: ss
  server: 185.153.197.5
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-lXknQ
  type: ss
  server: 113.99.143.139
  port: 26470
  cipher: aes-128-gcm
  password: b637f2e47b7827b308ebf399008075d2
- name: SS-aPlKs
  type: ss
  server: 3.9.17.198
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
- name: SSR-MWmCi
  type: ssr
  server: ssr.762988.xyz
  port: 33336
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-FM4Q3
  type: vmess
  server: v10.heduian.link
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-otgC2
  type: vmess
  server: 43.247.134.213
  port: 59516
  uuid: 2906e19e-c99f-456e-bcb3-c5472fd594e5
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-EnASS
  type: vmess
  server: 103.243.26.209
  port: 8080
  uuid: bc7e6840-ab83-4570-eaae-d9aff1e2da09
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: 103.243.26.209
- name: VMESS-AbsoL
  type: vmess
  server: 9438890c-t4whs0-t6blpv-1ldl3.hk.p5pv.com
  port: 80
  uuid: fd224a6c-addc-11ed-a8bf-f23c91cfbbc9
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-lV2AW
  type: vmess
  server: 43.247.134.213
  port: 59516
  uuid: 2906e19e-c99f-456e-bcb3-c5472fd594e5
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Pye1K
  type: vmess
  server: 103.127.218.91
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /1cef03ad
    headers:
      Host: ''
- name: VMESS-5XXX5
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-eXq22
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-eifuf
  type: vmess
  server: 2001:bc8:1203:209::50
  port: 23008
  uuid: e994b804-345c-4e8b-a827-7e005694d146
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: Trojan-xhpPT
  type: trojan
  server: 36.156.102.115
  port: 26876
  password: BxceQaOe
  params: 'allowInsecure: 1'
- name: Trojan-WgmhM
  type: trojan
  server: 58.152.46.98
  port: 443
  password: BxceQaOe
  params: 'allowInsecure: 1'
- name: Trojan-tuMS0
  type: trojan
  server: 36.151.251.23
  port: 4451
  password: BxceQaOe
  params: 'allowInsecure: 1'
- name: Trojan-uZ4gr
  type: trojan
  server: 160.16.236.32
  port: 2381
  password: ea39fa94f1ee00999337ea1fd3318e69
  params: 'allowInsecure: 0, sni: www.nintendogames.net'
- name: Trojan-xn2uw
  type: trojan
  server: 160.16.124.55
  port: 5041
  password: bca467b8c15211d189008a93c7519d3b
  params: 'allowInsecure: 1, sni: www.nintendogames.net'
- name: Trojan-q0dNI
  type: trojan
  server: 36.151.251.35
  port: 24392
  password: BxceQaOe
  params: 'allowInsecure: 1'
- name: Trojan-diGzx
  type: trojan
  server: 36.150.215.237
  port: 1821
  password: BxceQaOe
  params: 'allowInsecure: 1'
- name: Trojan-ahZ5Y
  type: trojan
  server: 160.16.240.91
  port: 3161
  password: bca467b8c15211d189008a93c7519d3b
  params: 'allowInsecure: 1, sni: www.baidu.com'
- name: Trojan-crXST
  type: trojan
  server: 160.16.204.136
  port: 2283
  password: bca467b8c15211d189008a93c7519d3b
  params: 'allowInsecure: 1, sni: www.baidu.com'
- name: Trojan-mY1PM
  type: trojan
  server: 160.16.236.32
  port: 2467
  password: ea39fa94f1ee00999337ea1fd3318e69
  params: 'allowInsecure: 0, sni: www.nintendogames.net'
- name: Trojan-6KzW1
  type: trojan
  server: oss-cn-shanghai.letssepub.com
  port: 20021
  password: adbac894-90b9-4913-b77e-a715a8d4ebc8
  params: 'allowInsecure: 0, sni: dingding-doc.com'
- name: Trojan-ynksC
  type: trojan
  server: 36.150.215.241
  port: 27409
  password: BxceQaOe
  params: 'allowInsecure: 1'
- name: Trojan-T0wVM
  type: trojan
  server: 160.16.240.91
  port: 4452
  password: bca467b8c15211d189008a93c7519d3b
  params: 'allowInsecure: 0, sni: www.nintendogames.net'
proxy-groups:
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - SS-PziAi
  - SS-jCUmz
  - SS-lXknQ
  - SS-aPlKs
  - SSR-MWmCi
  - VMESS-FM4Q3
  - VMESS-otgC2
  - VMESS-EnASS
  - VMESS-AbsoL
  - VMESS-lV2AW
  - VMESS-Pye1K
  - VMESS-5XXX5
  - VMESS-eXq22
  - VMESS-eifuf
  - Trojan-xhpPT
  - Trojan-WgmhM
  - Trojan-tuMS0
  - Trojan-uZ4gr
  - Trojan-xn2uw
  - Trojan-q0dNI
  - Trojan-diGzx
  - Trojan-ahZ5Y
  - Trojan-crXST
  - Trojan-mY1PM
  - Trojan-6KzW1
  - Trojan-ynksC
  - Trojan-T0wVM
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: ğŸŒ å›½å¤–åª’ä½“
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: â“‚ï¸ å¾®è½¯æœåŠ¡
  type: select
  proxies:
  - DIRECT
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
- name: ğŸ è‹¹æœæœåŠ¡
  type: select
  proxies:
  - DIRECT
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
- name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ® æ¸¸æˆå¹³å°
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ¬ YouTube
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ¥ Netflix
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ” å­¦æœ¯æœç´¢
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ›‘ å…¨çƒæ‹¦æˆª
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,clash.metacubex.one,DIRECT
- DOMAIN-KEYWORD,apple,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-KEYWORD,icloud,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,aaplimg.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.co,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple-cloudkit.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,appstore.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,cdn-apple.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,icloud.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,icloud-content.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,me.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,mzstatic.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.news,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.com.cn,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,appstore.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,icloud.com.cn,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-KEYWORD,microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,microsoft.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,msecnd.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,msedge.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,office.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,office.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,outlook.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,visualstudio.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,windows.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,windows.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,windowsupdate.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,xbox.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,xboxlive.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,msn.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,microsoftonline.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,microsoft365.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,skype.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,live.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,bing.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,hotmail.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,azureedge.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-KEYWORD,admarvel,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,admaster,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adsage,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adsmogo,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adsrvmedia,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adwords,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,analytics,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,duomeng,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,dwtrack,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,guanggao,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,lianmeng,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,mopub,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,omgmta,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,openx,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,partnerad,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,pingfore,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,supersonicads,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,tracking,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,uedas,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,umeng,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,usage,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,wlmonitor,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,zjtoolbar,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adjust.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,ad.gt,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adcolony.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adform.net,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,admob.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adnxs.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,ads-twitter.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adsafeprotected.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adsrvr.org,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,appsflyer.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,doubleclick.net,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googleadservices.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googleadsserving.cn,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googlesyndication.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googletagmanager.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googletagservices.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,mopub.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,telegra.ph,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telegram.org,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telegram.me,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telesco.pe,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,t.me,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,tdesktop.com,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telegramdownload.com,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- IP-CIDR,91.108.4.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.8.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.12.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.16.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.56.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,149.154.160.0/20,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,2001:b28:f23d::/48,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,2001:b28:f23f::/48,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,2001:67c:4e8::/48,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- DOMAIN-SUFFIX,steamcontent.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steampowered.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steamstatic.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steamcommunity.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,valvesoftware.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steam-chat.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,epicgames.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,epicgames.dev,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,unrealengine.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,playstation.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,playstation.net,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,playstationnetwork.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,sony.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,xbox.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,xboxlive.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,nintendo.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,nintendo.net,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,ea.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,origin.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,ubisoft.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,ubi.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,battle.net,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,blizzard.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,youtube.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,ytimg.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,googlevideo.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtu.be,ğŸ¬ YouTube
- DOMAIN-SUFFIX,yt.be,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtube-nocookie.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtubeeducation.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtubegaming.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtubekids.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,netflix.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflix.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflxext.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflximg.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflximg.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflxso.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflxvideo.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest0.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest1.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest2.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest3.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest4.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest5.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest6.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest7.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest8.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest9.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,scholar.google.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,scholar.googleusercontent.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,scholarcdn.net,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.tw,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.st,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.se,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.ren,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.ru,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,researchgate.net,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,springer.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sciencedirect.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,acm.org,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,ieee.org,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,nature.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,jstor.org,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,9cache.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,9gag.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,abc.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,bbc.co.uk,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,bbc.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,cnn.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,deezer.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,discord.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,dropbox.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,facebook.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,fb.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,fbcdn.net,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,github.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,github.io,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,githubusercontent.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,instagram.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,pinterest.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,reddit.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,redditmedia.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,redditstatic.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,spotify.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,tiktok.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,ttvnw.net,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,twitch.tv,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,twitter.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,x.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,t.co,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,medium.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,flickr.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,imgur.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,soundcloud.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,vimeo.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,tumblr.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,quora.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,reuters.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,nytimes.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,wsj.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,ft.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,theguardian.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,apnews.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,bloomberg.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,googlevideo.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,googleapis.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,gstatic.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,google.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,126.com,DIRECT
- DOMAIN-SUFFIX,126.net,DIRECT
- DOMAIN-SUFFIX,127.net,DIRECT
- DOMAIN-SUFFIX,163.com,DIRECT
- DOMAIN-SUFFIX,360buyimg.com,DIRECT
- DOMAIN-SUFFIX,36kr.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,aliyun.com,DIRECT
- DOMAIN-SUFFIX,alicdn.com,DIRECT
- DOMAIN-SUFFIX,amap.com,DIRECT
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-SUFFIX,bdimg.com,DIRECT
- DOMAIN-SUFFIX,bdstatic.com,DIRECT
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,caiyunapp.com,DIRECT
- DOMAIN-SUFFIX,csdn.net,DIRECT
- DOMAIN-SUFFIX,ctrip.com,DIRECT
- DOMAIN-SUFFIX,didi.com,DIRECT
- DOMAIN-SUFFIX,douban.com,DIRECT
- DOMAIN-SUFFIX,doubanio.com,DIRECT
- DOMAIN-SUFFIX,douyin.com,DIRECT
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,mi.com,DIRECT
- DOMAIN-SUFFIX,meituan.com,DIRECT
- DOMAIN-SUFFIX,meituan.net,DIRECT
- DOMAIN-SUFFIX,netease.com,DIRECT
- DOMAIN-SUFFIX,oschina.net,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,qqmail.com,DIRECT
- DOMAIN-SUFFIX,sina.com,DIRECT
- DOMAIN-SUFFIX,sinaimg.com,DIRECT
- DOMAIN-SUFFIX,taobao.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- DOMAIN-SUFFIX,tmall.com,DIRECT
- DOMAIN-SUFFIX,weibo.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,weixin.com,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,zhimg.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.net,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,iqiyipic.com,DIRECT
- DOMAIN-SUFFIX,acfun.cn,DIRECT
- DOMAIN-SUFFIX,aixifan.com,DIRECT
- DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
- DOMAIN-SUFFIX,xhscdn.com,DIRECT
- DOMAIN-SUFFIX,xiaomi.com,DIRECT
- DOMAIN-SUFFIX,xiaomiyoupin.com,DIRECT
- DOMAIN-SUFFIX,huawei.com,DIRECT
- DOMAIN-SUFFIX,hicloud.com,DIRECT
- DOMAIN-SUFFIX,vmall.com,DIRECT
- DOMAIN-SUFFIX,vivo.com,DIRECT
- DOMAIN-SUFFIX,oppo.com,DIRECT
- DOMAIN-SUFFIX,heytap.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
