port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies: []
proxy-groups:
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies: []
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
- name: å›½å¤–åª’ä½“
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  type: select
  proxies:
  - DIRECT
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
rule-providers:
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    format: text
    interval: 3600
    path: ./Clash/Apple.list
  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    format: text
    interval: 3600
    path: ./Clash/Telegram.list
  ProxyLite:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
    format: text
    interval: 3600
    path: ./Clash/ProxyLite.list
  ChinaDomain:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    format: text
    interval: 3600
    path: ./Clash/ChinaDomain.list
  ChinaCompanyIp:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    format: text
    interval: 3600
    path: ./Clash/ChinaCompanyIp.list
  ProxyMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    format: text
    interval: 3600
    path: ./Clash/ProxyMedia.list
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    format: text
    interval: 3600
    path: ./Clash/LocalAreaNetwork.list
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    format: text
    interval: 3600
    path: ./Clash/Microsoft.list
  GoogleCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    format: text
    interval: 3600
    path: ./Clash/GoogleCN.list
  BanAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    format: text
    interval: 3600
    path: ./Clash/BanAD.list
  BanProgramAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    format: text
    interval: 3600
    path: ./Clash/BanProgramAD.list
  SteamCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    format: text
    interval: 3600
    path: ./Clash/SteamCN.list
rules:
- RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
- RULE-SET,BanAD,ğŸ›‘ å…¨çƒæ‹¦æˆª
- RULE-SET,BanProgramAD,ğŸƒ åº”ç”¨å‡€åŒ–
- RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
- RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿
- RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
- RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
- RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
- RULE-SET,Telegram,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- RULE-SET,ProxyLite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
- RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿
- RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿
- GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
- MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
