port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - lens.l.google.com
  - +.qq.com
  - +.music.163.com
  - localhost
  - +.local
  - +.internal
  - '*.aliyuncs.com'
  - stun.*.*
  - stun.*.*.*
  - +.cdn.jsdelivr.net
  nameservers:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  - 1.1.1.1
  - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 224.0.0.0/4
    - 240.0.0.0/4
proxies:
- name: SS-QLP4D
  type: ss
  server: 79.127.200.169
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
- name: SS-swoim
  type: ss
  server: ss.039.node-for-bigairport.win
  port: 40402
  cipher: aes-256-gcm
  password: 792e0bdb-01db-450c-94c4-925151eb396e
- name: SS-zwLVm
  type: ss
  server: 208.67.106.73
  port: 44884
  cipher: chacha20-ietf-poly1305
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
- name: SS-MCTjT
  type: ss
  server: 103.35.189.136
  port: 443
  cipher: chacha20-ietf-poly1305
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
- name: SS-n6Zh1
  type: ss
  server: 51.195.203.247
  port: 8443
  cipher: chacha20-ietf-poly1305
  password: OMOpV2XCoMOBYsKGAjLDmsKkw6bDpMOkdVhtD15fwpQqw70AN8Krw6AyH8OaCQ==
- name: SS-nWbUl
  type: ss
  server: 193.135.174.135
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
- name: SS-wsyJP
  type: ss
  server: 103.253.74.94
  port: 31348
  cipher: chacha20-ietf-poly1305
  password: rNa753BcUuPBL8YxXx9Bx5b4dfVFu45QkzorwqZizTl6Af3N
- name: SS-Wkq49
  type: ss
  server: 38.60.250.107
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
- name: SS-S1Yau
  type: ss
  server: 45.12.136.170
  port: 443
  cipher: chacha20-ietf-poly1305
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
- name: SS-wCKlp
  type: ss
  server: 193.203.203.66
  port: 443
  cipher: chacha20-ietf-poly1305
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
- name: SS-Y29QX
  type: ss
  server: 185.213.23.63
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
- name: SS-fORj2
  type: ss
  server: 193.29.139.202
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
- name: SS-eTfgl
  type: ss
  server: 193.29.139.204
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
- name: VMESS-7Eowi
  type: vmess
  server: v30.hdacd.com
  port: 30830
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: bpbg.anguswen.top
- name: VMESS-UR8az
  type: vmess
  server: 2001:bc8:32d7:2013::8
  port: 62211
  uuid: e1786d49-ccba-466b-a0dd-e1ab59bd83bb
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-9v5N3
  type: vmess
  server: 154.29.157.189
  port: 38152
  uuid: b8ce19b1-4b15-41f9-a206-11957cc902d4
  alterId: 0
  cipher: none
  tls: false
  network: none
  none-opts:
    path: ''
    headers:
      Host: ''
- name: VMESS-lFyea
  type: vmess
  server: cf.fovi.tk
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: ''
  tls: true
  network: ws
  ws-opts:
    path: /eisasqa
    headers:
      Host: foxlux.fovi.tk
- name: VMESS-oslBt
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: VMESS-m7WbY
  type: vmess
  server: 216.167.107.61
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: none
  tls: false
  network: none
  none-opts:
    path: ''
    headers:
      Host: ''
- name: VMESS-mHfmX
  type: vmess
  server: 103.160.100.86
  port: 44222
  uuid: f703b128-2d32-4cdb-9608-f33c2d58abcc
  alterId: 0
  cipher: none
  tls: false
  network: none
  none-opts:
    path: ''
    headers:
      Host: ''
- name: Trojan-TzKrk
  type: trojan
  server: 58.152.25.71
  port: 443
  password: BxceQaOe
  params: 'allowInsecure: 1, sni: t.me/ripaojiedian'
- name: Trojan-1z9GL
  type: trojan
  server: 15.236.125.108
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, alpn: http/1.1, headerType: none, type: tcp, sni: trojan.burgerip.co.uk'
- name: Trojan-GLJOj
  type: trojan
  server: 58.152.110.104
  port: 443
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-7lmXV
  type: trojan
  server: 172.238.229.254
  port: 14051
  password: OdgHycGphesfLmPMYolUF
  params: 'security: tls, amp;sni: api.avito.ru, amp;allowInsecure: true, amp;fp:
    chrome'
- name: Trojan-efkiX
  type: trojan
  server: 107.174.82.102.sslip.io
  port: 443
  password: bb824a22-b7ce-427b-9ed6-1adf0751da02
  params: 'security: tls, type: ws, sni: 107.174.82.102.sslip.io, path: /gXKGj8a1tp1nNbZEcRugowKV'
- name: Trojan-NkJQk
  type: trojan
  server: cdnfire.xiaomispeed.com
  port: 23301
  password: 81fc5581-06e0-4d7e-9220-205af32a54d5
  params: 'sni: cdnfire.xiaomispeed.com'
- name: Trojan-bpmdS
  type: trojan
  server: 35.180.13.228
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, alpn: http/1.1, headerType: none, type: tcp, sni: trojan.burgerip.co.uk'
- name: Trojan-o7ahj
  type: trojan
  server: green2.cdntencentmusic.com
  port: 33301
  password: a5049baa-eadf-4523-bcac-33139e4a99ea
  params: 'sni: green2.cdntencentmusic.com'
- name: Trojan-sbtzi
  type: trojan
  server: 58.152.25.71
  port: 443
  password: BxceQaOe
  params: 'allowInsecure: 1, sni: t.me/ripaojiedian'
- name: Trojan-6bVmr
  type: trojan
  server: 35.158.205.73
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, alpn: http/1.1, headerType: none, type: tcp, sni: trojan.burgerip.co.uk'
- name: Trojan-HKwi8
  type: trojan
  server: 58.152.26.107
  port: 443
  password: BxceQaOe
  params: 'allowInsecure: 1, sni: t.me/ripaojiedian'
- name: Trojan-yJre9
  type: trojan
  server: 80.173.230.196
  port: 26279
  password: a5inYFE=JGV89+hjxIqgDp1tcWBd6
  params: 'security: tls, amp;sni: io.ozone.ru, amp;allowInsecure: true'
proxy-groups:
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - SS-QLP4D
  - SS-swoim
  - SS-zwLVm
  - SS-MCTjT
  - SS-n6Zh1
  - SS-nWbUl
  - SS-wsyJP
  - SS-Wkq49
  - SS-S1Yau
  - SS-wCKlp
  - SS-Y29QX
  - SS-fORj2
  - SS-eTfgl
  - VMESS-7Eowi
  - VMESS-UR8az
  - VMESS-9v5N3
  - VMESS-lFyea
  - VMESS-oslBt
  - VMESS-m7WbY
  - VMESS-mHfmX
  - Trojan-TzKrk
  - Trojan-1z9GL
  - Trojan-GLJOj
  - Trojan-7lmXV
  - Trojan-efkiX
  - Trojan-NkJQk
  - Trojan-bpmdS
  - Trojan-o7ahj
  - Trojan-sbtzi
  - Trojan-6bVmr
  - Trojan-HKwi8
  - Trojan-yJre9
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: ğŸŒ å›½å¤–åª’ä½“
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: â“‚ï¸ å¾®è½¯æœåŠ¡
  type: select
  proxies:
  - DIRECT
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
- name: ğŸ è‹¹æœæœåŠ¡
  type: select
  proxies:
  - DIRECT
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
- name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ® æ¸¸æˆå¹³å°
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ¬ YouTube
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ¥ Netflix
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ” å­¦æœ¯æœç´¢
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
- name: ğŸ›‘ å…¨çƒæ‹¦æˆª
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,clash.metacubex.one,DIRECT
- DOMAIN-KEYWORD,apple,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-KEYWORD,icloud,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,aaplimg.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.co,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple-cloudkit.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,appstore.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,cdn-apple.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,icloud.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,icloud-content.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,me.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,mzstatic.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.news,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,apple.com.cn,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,appstore.com,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-SUFFIX,icloud.com.cn,ğŸ è‹¹æœæœåŠ¡
- DOMAIN-KEYWORD,microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,microsoft.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,msecnd.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,msedge.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,office.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,office.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,outlook.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,visualstudio.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,windows.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,windows.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,windowsupdate.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,xbox.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,xboxlive.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,msn.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,microsoftonline.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,microsoft365.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,skype.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,live.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,bing.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,hotmail.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,azureedge.net,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-KEYWORD,admarvel,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,admaster,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adsage,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adsmogo,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adsrvmedia,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,adwords,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,analytics,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,duomeng,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,dwtrack,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,guanggao,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,lianmeng,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,mopub,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,omgmta,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,openx,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,partnerad,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,pingfore,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,supersonicads,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,tracking,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,uedas,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,umeng,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,usage,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,wlmonitor,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-KEYWORD,zjtoolbar,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adjust.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,ad.gt,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adcolony.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adform.net,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,admob.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adnxs.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,ads-twitter.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adsafeprotected.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,adsrvr.org,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,appsflyer.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,doubleclick.net,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googleadservices.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googleadsserving.cn,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googlesyndication.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googletagmanager.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,googletagservices.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,mopub.com,ğŸ›‘ å…¨çƒæ‹¦æˆª
- DOMAIN-SUFFIX,telegra.ph,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telegram.org,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telegram.me,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telesco.pe,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,t.me,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,tdesktop.com,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- DOMAIN-SUFFIX,telegramdownload.com,ğŸ“² ç”µæŠ¥ä¿¡æ¯
- IP-CIDR,91.108.4.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.8.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.12.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.16.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,91.108.56.0/22,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,149.154.160.0/20,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,2001:b28:f23d::/48,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,2001:b28:f23f::/48,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- IP-CIDR,2001:67c:4e8::/48,ğŸ“² ç”µæŠ¥ä¿¡æ¯,no-resolve
- DOMAIN-SUFFIX,steamcontent.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steampowered.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steamstatic.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steamcommunity.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,valvesoftware.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,steam-chat.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,epicgames.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,epicgames.dev,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,unrealengine.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,playstation.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,playstation.net,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,playstationnetwork.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,sony.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,xbox.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,xboxlive.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,nintendo.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,nintendo.net,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,ea.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,origin.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,ubisoft.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,ubi.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,battle.net,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,blizzard.com,ğŸ® æ¸¸æˆå¹³å°
- DOMAIN-SUFFIX,youtube.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,ytimg.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,googlevideo.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtu.be,ğŸ¬ YouTube
- DOMAIN-SUFFIX,yt.be,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtube-nocookie.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtubeeducation.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtubegaming.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,youtubekids.com,ğŸ¬ YouTube
- DOMAIN-SUFFIX,netflix.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflix.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflxext.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflximg.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflximg.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflxso.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,nflxvideo.net,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest0.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest1.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest2.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest3.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest4.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest5.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest6.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest7.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest8.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,netflixdnstest9.com,ğŸ¥ Netflix
- DOMAIN-SUFFIX,scholar.google.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,scholar.googleusercontent.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,scholarcdn.net,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.tw,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.st,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.se,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.ren,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sci-hub.ru,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,researchgate.net,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,springer.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,sciencedirect.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,acm.org,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,ieee.org,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,nature.com,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,jstor.org,ğŸ” å­¦æœ¯æœç´¢
- DOMAIN-SUFFIX,9cache.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,9gag.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,abc.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,bbc.co.uk,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,bbc.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,cnn.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,deezer.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,discord.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,dropbox.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,facebook.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,fb.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,fbcdn.net,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,github.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,github.io,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,githubusercontent.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,instagram.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,pinterest.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,reddit.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,redditmedia.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,redditstatic.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,spotify.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,tiktok.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,ttvnw.net,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,twitch.tv,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,twitter.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,x.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,t.co,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,medium.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,flickr.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,imgur.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,soundcloud.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,vimeo.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,tumblr.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,quora.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,reuters.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,nytimes.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,wsj.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,ft.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,theguardian.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,apnews.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,bloomberg.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,googlevideo.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,googleapis.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,gstatic.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,google.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,126.com,DIRECT
- DOMAIN-SUFFIX,126.net,DIRECT
- DOMAIN-SUFFIX,127.net,DIRECT
- DOMAIN-SUFFIX,163.com,DIRECT
- DOMAIN-SUFFIX,360buyimg.com,DIRECT
- DOMAIN-SUFFIX,36kr.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,aliyun.com,DIRECT
- DOMAIN-SUFFIX,alicdn.com,DIRECT
- DOMAIN-SUFFIX,amap.com,DIRECT
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-SUFFIX,bdimg.com,DIRECT
- DOMAIN-SUFFIX,bdstatic.com,DIRECT
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,caiyunapp.com,DIRECT
- DOMAIN-SUFFIX,csdn.net,DIRECT
- DOMAIN-SUFFIX,ctrip.com,DIRECT
- DOMAIN-SUFFIX,didi.com,DIRECT
- DOMAIN-SUFFIX,douban.com,DIRECT
- DOMAIN-SUFFIX,doubanio.com,DIRECT
- DOMAIN-SUFFIX,douyin.com,DIRECT
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,mi.com,DIRECT
- DOMAIN-SUFFIX,meituan.com,DIRECT
- DOMAIN-SUFFIX,meituan.net,DIRECT
- DOMAIN-SUFFIX,netease.com,DIRECT
- DOMAIN-SUFFIX,oschina.net,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,qqmail.com,DIRECT
- DOMAIN-SUFFIX,sina.com,DIRECT
- DOMAIN-SUFFIX,sinaimg.com,DIRECT
- DOMAIN-SUFFIX,taobao.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- DOMAIN-SUFFIX,tmall.com,DIRECT
- DOMAIN-SUFFIX,weibo.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,weixin.com,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,zhimg.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.net,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,iqiyipic.com,DIRECT
- DOMAIN-SUFFIX,acfun.cn,DIRECT
- DOMAIN-SUFFIX,aixifan.com,DIRECT
- DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
- DOMAIN-SUFFIX,xhscdn.com,DIRECT
- DOMAIN-SUFFIX,xiaomi.com,DIRECT
- DOMAIN-SUFFIX,xiaomiyoupin.com,DIRECT
- DOMAIN-SUFFIX,huawei.com,DIRECT
- DOMAIN-SUFFIX,hicloud.com,DIRECT
- DOMAIN-SUFFIX,vmall.com,DIRECT
- DOMAIN-SUFFIX,vivo.com,DIRECT
- DOMAIN-SUFFIX,oppo.com,DIRECT
- DOMAIN-SUFFIX,heytap.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
